Pequenas mudanças no back-end
Rodrisc/Encurtador_de_Links pull request #1
Opened 2022-05-30 21:19 UTC by Rodrisc

Alterações e correções para o uso correto da linguagem, alterações dos nomes das variáveis para melhor leitura.

2022-05-30 23:26 UTC, pedroven requested changes
No geral está ok, no entanto, seria bom refatorar para algo próximo do que eu tinha mencionado anteriormente (separação dos arquivos, criação de novas funções e etc).

2022-05-30 23:26 UTC, pedroven commented on back-end/PythonMain.py
> +        print(retorno_da_url)
Deveria remover o print

2022-05-30 23:26 UTC, pedroven commented on back-end/saveDB.py
>      #conex = sql.connect(host='localhost', database='python', user='postgres', password='8850')
deveria ser removido esse comentário

2022-05-30 23:26 UTC, pedroven commented on back-end/saveDB.py
> +    print(lista)
remover o print

2022-05-30 23:26 UTC, pedroven commented on back-end/saveDB.py
> +    lista = cursor.fetchone()
o nome não deveria ser lista, já que o fetchone só retorna um objeto

2022-05-30 23:26 UTC, pedroven commented on back-end/saveDB.py
> +        print(verificar_hash)
remover print

2022-05-30 23:26 UTC, pedroven commented on front-end/src/index.css
> +.h510p{
Por que esse nome de classe?

2022-06-03 18:38 UTC, Rodrisc commented on back-end/PythonMain.py
> +        print(retorno_da_url)
Resolvido

2022-06-03 18:38 UTC, Rodrisc commented on back-end/saveDB.py
>      #conex = sql.connect(host='localhost', database='python', user='postgres', password='8850')
Resolvido

2022-06-03 18:39 UTC, Rodrisc commented on back-end/saveDB.py
> +    print(lista)
Resolvido

2022-06-03 18:39 UTC, Rodrisc commented on back-end/saveDB.py
> +    lista = cursor.fetchone()
Resolvido

2022-06-03 18:39 UTC, Rodrisc commented on back-end/saveDB.py
> +        print(verificar_hash)
Resolvido

2022-06-03 18:42 UTC, Rodrisc commented on front-end/src/index.css
> +.h510p{
Resolvido

2022-06-04 01:20 UTC, merged