Modularizacao
Rodrisc/Encurtador_de_Links pull request #2
Opened 2022-06-04 02:02 UTC by Rodrisc

Separação dos componentes do React

2022-06-06 13:23 UTC, pedroven requested changes
Só precisa de pequenos ajustes, no entanto o arquivo index.js, não deveria ter o componente principal (App), esse componente deveria estar num arquivo a parte, como por exemplo: src/App.js

2022-06-06 13:23 UTC, pedroven commented on front-end/src/index.js
>          await axios.post('http://localhost:5000/savelink', JSON.parse(`{"link": "${link}" }`)).then((response) => {
deveria mudar para receber o valor numa variável, fazendo melhor uso do async await. (JSON.parse() não é necessário pq o axios faz isso internamente)
```suggestion
        const { data } = await axios.post('http://localhost:5000/savelink', {link: link});
        setUrl(data.link);
        setLink('');
```

2022-06-06 13:26 UTC, pedroven approved these changes

2022-06-06 13:26 UTC, pedroven requested changes
Só precisa de pequenos ajustes, no entanto o arquivo index.js, não deveria ter o componente principal (App), esse componente deveria estar num arquivo a parte, como por exemplo: src/App.js

2022-06-07 02:08 UTC, Rodrisc commented on front-end/src/index.js
>          await axios.post('http://localhost:5000/savelink', JSON.parse(`{"link": "${link}" }`)).then((response) => {
Resolvido, assim fica até mais fácil.

2022-06-07 19:54 UTC, pedroven approved these changes
LGTM

2022-06-07 19:59 UTC, merged