funcao para conectar banco
Rodrisc/Encurtador_de_Links pull request #3
Opened 2022-06-09 01:25 UTC by Rodrisc

criada a funcao para conectar ao bando de dados

2022-06-09 14:37 UTC, pedroven approved these changes
Pra uma aplicação desse tamanho, a implementação atual está ok. No entanto, para aplicações maiores, seria necessário uma outra abordagem. Sugiro estudar alguns conceitos para o futuro: Connection pools, Singleton Pattern e SOLID.

2022-06-17 22:47 UTC, pedroven requested changes

2022-06-17 22:47 UTC, pedroven commented on back-end/db.py
> +    return cursor.fetchone()
```suggestion
    return cursor.fetchone()
conexao, cursor = conectar_banco()
```
retornar a conexão e o cursor como variáveis globais desse módulo

2022-06-17 22:47 UTC, pedroven commented on back-end/db.py
> +def conetar_banco():
renomear para conectar_banco()

2022-06-17 22:47 UTC, pedroven commented on back-end/routes/__init__.py
> +from flask import Flask
esse módulo não precisa existir

2022-06-17 22:47 UTC, pedroven commented on back-end/db.py
> +import random
como os outros módulos estão sendo nomeados em português, esse também deveria estar. deveria ser bd.py

2022-06-17 22:47 UTC, pedroven commented on back-end/routes/rotas.py
> +from routes import app, conex, cursor
aqui a conexão e o cursor deveriam ser importados do módulo de banco de dados, já que eles não tem origem nas rotas

2022-06-17 22:47 UTC, pedroven commented on back-end/run.py
> +
```suggestion
app = Flask(__name__)
CORS(app)
```

2022-06-17 22:47 UTC, pedroven commented on back-end/run.py
> +from routes import app
renomear para app.py, para ser mais semântico

2022-06-17 22:47 UTC, pedroven commented on front-end/src/App.js
>          let TextoCopiado = url
letra maiúscula para variável passa a ideia de classe, e nesse caso nem tem necessidade de se utilizar uma váriável já que você pode usar o estado de forma direta.

2022-06-17 22:47 UTC, pedroven commented on front-end/src/App.js
> +        if(posicao_do_ponto !== -1 & link !== "" & str_dps_ponto.length >= 2){
Para concatenar condições, não se usa "&" (esse é um operador bit a bit) se usa "&&" https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Expressions_and_operators . e essa condição não vai salvar uma url válida como essa:   https://github.com/datadolphyn/R/blob/master/DefaultChartForPAD.R

2022-06-18 15:49 UTC, Rodrisc commented on back-end/db.py
> +    return cursor.fetchone()
Resolvido

2022-06-18 15:50 UTC, Rodrisc commented on back-end/db.py
> +def conetar_banco():
resolvido

2022-06-18 15:56 UTC, Rodrisc commented on back-end/db.py
> +import random
Resolvido

2022-06-18 15:59 UTC, Rodrisc commented on back-end/run.py
> +from routes import app
resolvido

2022-06-18 16:02 UTC, Rodrisc commented on front-end/src/App.js
>          let TextoCopiado = url
Bem observado. Resolvido

2022-06-18 19:59 UTC, pedroven approved these changes
LGTM

2022-06-18 21:03 UTC, merged